### ISSUE TITLE
id: 81ow3i7lnhnivs9 verify Uniswap

### ISSUE THREAD

**Issue by davaymne** [ovrclk/awesome-akash#24]
akash provider lease-status:

{
  "services": {
    "web": {
      "name": "web",
      "available": 1,
      "total": 1,
      "uris": [
        "mt60bmuka993hbirvq0fis7ubk.provider4.akashdev.net"
      ],
      "observed-generation": 0,
      "replicas": 0,
      "updated-replicas": 0,
      "ready-replicas": 0,
      "available-replicas": 0
    }
  },
  "forwarded-ports": {}
}

<img width="1723" alt="Screenshot 2020-12-07 at 23 20 49" src="https://user-images.githubusercontent.com/29555611/101432547-f64da900-3900-11eb-9e21-d68b01652034.png">

**Comment by boz** [comment]
Looks great!
